os: osx
language: swift
osx_image: xcode11.5
before_install:
  - gem install bundler -v $(cat Gemfile.lock | tail -1)
  - bundle update
  - bundle install
script:
  - bundle exec fastlane tests
  - bundle exec fastlane coverage
after_success:
  - bash <(curl -s https://codecov.io/bash) -D derivedData -J Optimal-Cayo-Perico-Take -X gcov -f output/cobertura/cobertura.xml
